config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'users/new'

  root 'static_pages#home'

  get  '/home',    to: 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/filtercontent',    to: 'static_pages#home'

  post '/home',    to: 'static_pages#filter'
  post '/filtercontent',    to: 'static_pages#filtercontent'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/microposts', to: 'microposts#new'
  post '/microposts', to: 'microposts#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/my_comments', to: 'users#my_comments'
  get '/my_posts', to: 'users#my_posts'
  get '/comments', to: 'users#comments'
  
  
  resources :users do
    resources :comments, module: :users
  end

  resources :microposts, only: [:create, :destroy, :show, :new]
  resources :microposts do
    resources :comments, module: :microposts
  end
  
  resources :comments
  resources :comments do
    resources :comments, module: :comments
  end


  resources :password_resets, only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token, :reset_token
    before_save :downcase_email

    has_many :microposts, dependent: :destroy
    has_many :comments, as: :commentable, dependent: :destroy
    before_save{self.email=email.downcase}

    mount_uploader :avatar, PhotoUploader
    mount_uploader :card, PhotoUploader
    validate :avatar_size
    validate :card_size
    validates :name, presence: true, length: { maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255},
                      format: {with: VALID_EMAIL_REGEX},
                      uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, presence: true, length: {minimum: 8, maximum: 20}, allow_nil: true
    validates :phonenumber, length: {minimum: 10, maximum: 13}, allow_nil: true, allow_blank: true


    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end 

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

    def feed
        Micropost.where("user_id = ?", id)
    end

    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end
    
    # Sends password reset email.
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

    private

        def downcase_email
            self.email = email.downcase
        end

        def card_size
            if card.size > 5.megabytes
                errors.add(:card, "should be less than 5mb")
            end
        end

        def avatar_size
            if avatar.size > 5.megabytes
                errors.add(:avatar, "should be less than 5mb")
            end
        end    
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < CommentsController
    before_action :set_commentable

    private

        def set_commentable
            @commentable = User.find(params[:user_id])
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :my_comments]  
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  def show
    @user = User.find(params[:id])    
    @microposts = @user.microposts.paginate(page: params[:page])
    @comments = Comment.where(user_id: @user.id)
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # successful save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:sucess] = "User deleted"
    redirect_to users_url
  end

  def my_comments
    @user = current_user
    @posts = current_user.microposts
    @my_comments = []

    if @posts.any?
      @comments = @posts.first.comments
      @posts.each do |post|
        if post.comments.any?
          @comments.push(post.comments)
        end
      end

      @comments.each do |comment|
        @my_comments.push(comment)
      end
    end
  end

  def my_posts
    @user = current_user    
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def comments
    @user = current_user
    @comments = Comment.where(user_id: @user.id)
  end

  private
    
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,
                                  :city, :phonenumber, :avatar, :card, :card_number)
    end

    # Confirms the correct user.
    def correct_user  
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar rounded mx-auto d-block")
  end

end

app/views/users/_comments_on_my_posts.html.erb
<% if micropost.comments.any? %>
<% micropost.comments.each do |comment| %>
  <div class="well" style="margin-left: 30px;">
    <p style="font-size: 12px;"><%= link_to User.find(comment.user_id).name, User.find(comment.user_id) %> commented at <span style="text-muted"><%= comment.created_at %>: </p>
    <%= raw comment.body %>
  </div>
<% end %>
<br/><hr/>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f|%>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'%>

    <%= f.label :email %>
    <%= f.email_field :email , class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit 'sign up', class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: 50%>
    <%= link_to user.name, user%>
    <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: {confirm: "You sure?" } %>
    <% end %>
</li>

app/views/users/_user_info.html.erb
    <div class="col-md-12", style="margin-top: 50px;">
    <!-- <%= gravatar_for @user%>  -->
      <div class="row text-center">
        <% if @user.avatar? %>
          <%= image_tag(@user.avatar.url, size: 150, class:"rounded mx-auto d-block") %>
        <% else %>
          <%= gravatar_for(@user, size: 150)%>
        <% end %>
      </p>
      </div>
        <p class="text-center">Name: <%= @user.name %></p>
        <p class="text-muted text-center"><i class="glyphicon glyphicon-time"></i>  <%= @user.created_at.strftime("%Y-%m-%d")%>
        <% if @user.city? %>
          <span style="margin-right: 40px;"></span><i class="glyphicon glyphicon-map-marker"></i>  <%= @user.city %></p>
        <% end %>
    </div>

app/views/users/comments.html.erb
<% provide(:title, @user.name) %>
<div>
    <%= render 'users/user_info' %>
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h6>My Comments</h6>
        </div>
        <div class="panel-body">
          <% if @comments.any? %>
          <% @comments.each do |comment| %>
          <div>
            <p class="panel-text">
              <p><%= raw comment.body %></p>
              <span style="float:right;">in Post: <%= link_to Micropost.find(comment.micropost_id).title, Micropost.find(comment.micropost_id) %> 
              by <%= link_to User.find(Micropost.find(comment.micropost_id).user_id).name, User.find(Micropost.find(comment.micropost_id).user_id) %></span>
            </p>
            <br/>
            <p style="float: right;"><small class="text-muted">Written at: <%= comment.created_at %></small></p>
            <br/>
            <br/> 
            <p style="float: right;"><small class="text-muted">
              <%= link_to "delete this comment?", comment, method: :delete, data: { confirm: "You sure?"} %> 
            </small></p>
            <br/><hr/>
          </div>
          <% end %>

          <% else %>
          <p class="panel-text">User has no comments</p>
          <% end %>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%provide(:title,"Edit user")%>
<% provide(:button_text, 'Save changes')%>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-2 col-xs-2">
    <div class="panel" style="background-color: #222; padding-bottom:  230px;">
      <ul role="navigation" class="nav nav-pills nav-stacked" style="max-width: 250px;" id="sidebar">
        <li>
          <%= link_to current_user , class:"nav-link" do %>
            <span><i class="glyphicon glyphicon-send" aria-hidden="true" style="margin-right: 10px;"></i> My profile</span> 
          <% end %>
        </li>
        <li>
          <%= link_to my_posts_path , class:"nav-link" do %>
            <span><i class="glyphicon glyphicon-user" aria-hidden="true" style="margin-right: 10px;"></i> My Posts</span> 
          <% end %>
        </li>
        <li>
          <%= link_to comments_path , class:"nav-link" do %>
            <span><i class="glyphicon glyphicon-comment" aria-hidden="true" style="margin-right: 10px;"></i> My Comments</span> 
          <% end %>
        </li>
        <li>
          <%= link_to my_comments_path , class:"nav-link" do %>
            <span><i class="glyphicon glyphicon-ok-sign" aria-hidden="true" style="margin-right: 10px;"></i> Comments to me</span> 
          <% end %>
        </li>
        <li class="active">
          <%= link_to edit_user_path(current_user), class:"nav-link" do %>
            <span><i class="glyphicon glyphicon-cog" aria-hidden="true" style="margin-right: 10px;"></i> My Settings</span> 
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  
  <div class="col-md-10">
    <div class="panel panel-default">
      <div class="panel panel-body">
        <ul class="nav nav-tabs">
          <li role="presentation" class="active"><a data-toggle="tab" href="#home">Personal Info</a></li>
          <li role="presentation"><a data-toggle="tab" href="#avatar">Avatar</a></li>
          <li role="presentation"><a data-toggle="tab" href="#password">Password</a></li>
          <li role="presentation"><a data-toggle="tab" href="#verification">Verification</a></li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <div role="tabpanel" class="tab-pane fade in active" id="home">
            <div class="col-md-6" style="margin-top: 20px; ">
              <%= form_for(@user) do |f|%>
              <%= render 'shared/error_messages', object: f.object %>

              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control"%>

              <%= f.label :email %>
              <%= f.email_field :email , class: "form-control" %>

              <%= f.label :phonenumber %> 
              <%= f.text_field :phonenumber, class:"form-control" %>

              <%= f.label :city %> 
              <%= f.text_field :city, class:"form-control" %>


              <%= f.submit 'Confirm', class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>

          <div class="tab-pane fade" id="avatar" role="tabpanel">
            <div class="col-md-6" style="margin-top: 20px;">
              <% if @user.avatar? %>
                <%= image_tag(@user.avatar.url, size: "300") %>
              <% else %>
                <%= gravatar_for @user %>
              <% end %>

              <%= form_for(@user) do |f| %> 
              <%= render'shared/error_messages'%>
              <div style="margin-top: 20px;">
                <%= f.file_field :avatar %>
              </div>
              <%= f.submit "Confirm", class:"btn btn-primary"%>
              <%end%>
            </div>
          </div>
          <div class="tab-pane fade" id="password" role="password">
            <div class="col-md-6" style="margin-top: 20px;">
              <%= form_for(@user) do |f| %> <%= render'shared/error_messages'%>
              <%= f.label :password %>
              <%= f.password_field :password, class:"form-control" %>
              <%= f.label :password_confirmation, "Confirm Password" %>
              <%= f.password_field :password_confirmation,class:"form-control" %>
              <%= f.submit "Confirm", class:"btn btn-primary"%>
              <%end%>
            </div>
          </div>

          <div class="tab-pane fade" id="verification" role="tabpanel" aria-labelledby="verify-tab">
            <div class="col-md-6" style="margin-top: 20px;">
              <%= image_tag(@user.card.url, size: "400") if @user.card? %>
              <%= form_for(@user) do |f| %> 
                <%= render'shared/error_messages'%>
                <div class="form-group">
                  <%= f.label :card_number %>
                  <%= f.text_field :card_number, class: 'form-control', id: "number"%>
                </div>
                <div class="form-group">
                  <%= f.file_field :card %>
                </div>
                <%= f.submit "Confirm", class:"btn btn-primary"%>
              <%end%>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type = "text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/my_comments.html.erb
<% provide(:title, @user.name) %>
<div>
    <%= render 'users/user_info' %>
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h6>Comments to me</h6>
        </div>
        <div class="panel-body">
          <% if @my_comments.any? %>
          <% @my_comments.each do |comment| %>
          <div>
            <p class="panel-text">
              <%= link_to User.find(comment.user_id).name, User.find(comment.user_id) %> commented:
              <span style="float:right;">in Post: <%= link_to Micropost.find(comment.micropost_id).title, Micropost.find(comment.micropost_id) %> 
              by <%= link_to User.find(Micropost.find(comment.micropost_id).user_id).name, User.find(Micropost.find(comment.micropost_id).user_id) %></span>
            </p>
            <p style="margin-left: 30px;">
              <%= raw comment.body %> 
            </p>
            <p style="float: right;"><small class="text-muted">Written at: <%= comment.created_at %></small></p>
            <br/><hr/>
          </div>
          <% end %>

          <% else %>
          <p class="panel-text">User has no comments</p>
          <% end %>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/my_posts.html.erb
<% provide(:title, @user.name) %>
<div>
  <%= render 'users/user_info' %>
  <div class="row" style="margin-bottom: 30px;">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h6>My Posts</h6>
        </div>
        <div class="panel-body">
          <% if @microposts.any? %>
          <% @microposts.each do |micropost| %>
            <div>
              <p class="panel-text"><%= link_to micropost.user.name, micropost %> posted <%= link_to micropost.title, micropost %> 
              <span><small class="text-muted">at <%= micropost.created_at %></small></span>:</p>
              <p class="panel-text"><%= raw micropost.content %></p>
            </div>
            <br>
            <hr/>
            <%= render partial: "users/comments_on_my_posts", locals: {micropost: micropost}%>
          <% end %>
          <% else %>
          <p class="panel-text">User has no posts</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide( :title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
      <br/>
      <p><%= link_to "Already a user?", login_path %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <%= render 'users/user_info' %>
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h6>My Posts</h6>
        </div>
        <div class="panel-body">
          <% if @microposts.any? %>
          <% @microposts.each do |post| %>
            <div>
              <p class="panel-text"><%= link_to post.title, post %></p>
              <p style="float: right;"><small class="text-muted"><%= post.created_at %></small></p>
            </div>
            <br>
            <hr/>
          <% end %>
          <% else %>
          <p class="panel-text">User has no posts</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h6>My Comments</h6>
        </div>
        <div class="panel-body">
          <% if @comments.any? %>
          <% @comments.each do |comment| %>
          <div>
            <p class="panel-text">
              <p><%= raw comment.body %></p>
              <span style="float:right;">in Post: <%= link_to Micropost.find(comment.micropost_id).title, Micropost.find(comment.micropost_id) %> 
              by <%= link_to User.find(Micropost.find(comment.micropost_id).user_id).name, User.find(Micropost.find(comment.micropost_id).user_id) %></span>
            </p>
            <br/>
            <p style="float: right;"><small class="text-muted">Written at: <%= comment.created_at %></small></p>
            <br/><hr/>
          </div>
          <% end %>

          <% else %>
          <p class="panel-text">User has no comments</p>
          <% end %>
          
        </div>
      </div>
    </div>
  </div>
</div>