config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'users/new'

  root 'static_pages#home'

  get  '/home',    to: 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/filtercontent',    to: 'static_pages#home'

  post '/home',    to: 'static_pages#filter'
  post '/filtercontent',    to: 'static_pages#filtercontent'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/microposts', to: 'microposts#new'
  post '/microposts', to: 'microposts#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/my_comments', to: 'users#my_comments'
  get '/my_posts', to: 'users#my_posts'
  get '/comments', to: 'users#comments'
  
  
  resources :users do
    resources :comments, module: :users
  end

  resources :microposts, only: [:create, :destroy, :show, :new]
  resources :microposts do
    resources :comments, module: :microposts
  end
  
  resources :comments
  resources :comments do
    resources :comments, module: :comments
  end


  resources :password_resets, only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_external_links.html.erb
    <div>
        <a class="external-link col-sm-3 btn btn-info" href="https://www.learnenough.com/ruby-on-rails-6th-edition#landing-pricing?gclid=CjwKCAjwqpP2BRBTEiwAfpiD-wvHVj4DHhIXzxnCVTvLn6H4f0xTQVTRH5XiLjmPUrThC6mIrasRvhoCkRcQAvD_BwE">Rails</a>
        <a class="external-link col-sm-3 btn btn-info col-sm-offset-1" href="https://www.rmit.edu.vn/">RMIT</a>
    </div>
    <div class="row customized-container-search" style="padding-top: 50px">
    </div>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_filter_form.html.erb
<% if false %>
<%= button_to "2", home_path, params: {topic: "2"} %>
<%= button_to "topic", home_path, params: {topic: "topic"} %>
<% end %>


<%= form_for :static_pages, url: home_path, :html => {:id => "filter_form"} do |f| %>

    <div data-toggle="buttons" class="micropost-filter-form" >
        <% $topic.each do |t| %>
        <label class="btn btn-info col-sm-3" style="margin: 0px 15px 15px 15px;">
            <%= check_box_tag "topic[]", t %> <%= t %>
        </label>
        <% end  %>
    </div>
    <div class="row customized-container-search" style="padding-top: 50px">
    </div>
<% end %>


<% if false %>
<%= simple_form_for :static_pages, url: filter_path do %>

    <%= text_field :myform, :topic %>

    <%= submit_tag 'sign up', class: "btn btn-primary" %>
<% end %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="field">
    <%= f.text_area :title, class: "smalltextarea", placeholder: "Enter post title..." %>
    <%= f.text_area :topic, class: "smalltextarea", placeholder: "Enter post topic..." %>
    <%= f.text_area :content, class: "customtextarea", placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_most_viewed_posts.html.erb
<div class="panel">
<% @most_viewed_posts.each do |post| %>
<ol class="microposts">
    <li style="padding-left: 20px; padding-right: 50px; padding-top: 10px;"><%= link_to post.title, post %></li>
    <small><i class="glyphicon glyphicon-eye-open" style="float: right; padding-right: 20px;">  <%= post.view %></i></small>
</ol>
<br>
<%end%>
</div>

app/views/shared/_recent_posts.html.erb
 <% @recent_posts.each do |post| %> 
    <div class="panel"> 
    <div class="panel-body">
    <div class ="row">
    <div class ="col-md-2">
    <div class="panel-img" style="margin-left: 20px; margin-top: 20px;">
        <% if post.user.avatar? %>
        <%= link_to image_tag(post.user.avatar.url, size: 70), post.user %>
        <% else %>
        <%= link_to gravatar_for(post.user, size: 70), post.user%> 
        <% end %>
    </div>
    </div>
    <div class ="col-md-9">
    <div class="panel-title">
        <h3 class="post-title"><%= link_to post.title, post %></h3>
    </div>
    <div class="panel-text">
    <div class="post-info">
        <p class="user"><small class="text-muted"><%= link_to post.user.name, post.user %> </small></p>        
        <p class="panel-text">
        <small class="text-muted">  
            Posted <%= time_ago_in_words(post.created_at) %> ago 
        </small>    
        </p>  
        <p class="card-text"><small class="text-muted"><%= post.topic %></small></p>   
        </div>
        <div class="post-corner" >
            <small> <i class="glyphicon glyphicon-comment"> </i> <%= post.comments.count %></i></i></small> 
            <span style="margin-right: 20px;"></span>
            <small> <i class="glyphicon glyphicon-eye-open"> </i> <%= post.view %></i></i></small>
        </div>
        
       </div>    
    </div>
    </div>      
    </div>
    </div>
    <% end %>

<%= will_paginate @recent_posts%>

app/views/shared/_secondary_navbar.html.erb
<div class="panel">
<div class="tab topnav" style="padding-left: 0px;">
    <%= link_to "Recent posts", root_path, class: "tablinks"%>
    <%= link_to "Selected posts", root_path, :onclick => "$(filter_form).submit()"%>
    <%= link_to "New Post", microposts_path, class: "tablinks newpost", style: "float: right;" %>
    <% if logged_in? %>
    <%= link_to "My Settings", edit_user_path(current_user), class: "tablinks"%>
    <% end %>
    <div class="search-container">
      <%= form_for :static_pages, url: filtercontent_path, :html => {:id => "filter_content_form"} do |f| %>
        <%= text_field_tag :content %>
      <% end %>
      <%= link_to "", root_path, :onclick => "$(filter_content_form).submit()", class: "glyphicon glyphicon-search"%>
    </div>
</div> 
</div>

app/views/shared/_side_bar.html.erb
    <div class="col-md-4" style="margin-top: 50px;">
      <div class="side-bar">
        <div class="panel">
          <div class="panel-body">
            <h4 class="session-title"> Recent Members </h4>

            <div style="margin: 15px 15px 15px 15px">
              <% @user_ids.each do |user_id| %>
              <% user = User.find_by(id: user_id) %>
                <div class="col-sm-2 col-sm-offset-1" style="margin-right: 10px;">
                <% if user.avatar? %>
                  <%= link_to image_tag(user.avatar.url, size: 60), user %>
                <% else %>
                  <%= link_to gravatar_for(user, size: 60), user %> 
                <% end %>
                  <p class="text-center" style="font-size: 12px;"><%= link_to user.name, user %></p>
                </div>
              <% end %>
            </div>

          </div>
        </div>

        <br/>
        <div class="panel">
          <div class="panel-body">
            <h4 class="session-title"> Topic </h4>

            <div style="padding: 15px 15px 15px 15px">
              <%= render 'shared/micropost_filter_form' %>
            </div>
            
          </div>
        </div>

        <br/>

        <div class="card">
          <div class="card-body">
            <h4 class="session-title"> Post </h4>

            <div style="padding: 15px 15px 15px 15px">
              <%= render 'shared/most_viewed_posts' %>
            </div>
            
          </div>
        </div>

        <div class="card">
          <div class="card-body">
            <h4 class="session-title"> External Links </h4>
            <div style="padding: 15px 15px 15px 15px">
              <%= render 'shared/external_links' %>
              
            </div>
            
          </div>
        </div>

        <div style="margin-bottom: 50px;">
        </div>

      </div>
    </div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user,size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count,"micropost") %></span>