config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'users/new'

  root 'static_pages#home'

  get  '/home',    to: 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/filtercontent',    to: 'static_pages#home'

  post '/home',    to: 'static_pages#filter'
  post '/filtercontent',    to: 'static_pages#filtercontent'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/microposts', to: 'microposts#new'
  post '/microposts', to: 'microposts#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/my_comments', to: 'users#my_comments'
  get '/my_posts', to: 'users#my_posts'
  get '/comments', to: 'users#comments'
  
  
  resources :users do
    resources :comments, module: :users
  end

  resources :microposts, only: [:create, :destroy, :show, :new]
  resources :microposts do
    resources :comments, module: :microposts
  end
  
  resources :comments
  resources :comments do
    resources :comments, module: :comments
  end


  resources :password_resets, only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class = "footer">
  <div>Copyright&copy; 2020 |
    <span> Powered by {Zhang Junhao - s3714056} {Tran Gia Hung - s3715272} | Tutorial Group 3 | {Tutor: Anto Dominic}</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar-right">
  <div class="customized-container">
    <%= link_to "Ruby App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav" style="margin-left: 30%;">
        <li><%= link_to "Home", root_path %></li>
      </ul>

        <% if logged_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to current_user.name, current_user %></li>
          <li class="dropdown">
            <a class="navbar-gravatar" data-toggle="dropdown">News</a>
            <ul class="dropdown-menu">
              <% $most_popular_topics.each do |t| %>
                <li><%= link_to t[0], {controller: 'static_pages', action:'filter', topic: t[0]}, method: :post %></li>
              <% end %>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a class="navbar-gravatar" data-toggle="dropdown">
              <% if current_user.avatar? %>
              <%= image_tag(current_user.avatar.url, size:30) %>
              <% else %>
              <%= gravatar_for(current_user, size: 30) %>
              <% end %>
            </a>
            
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Log in", login_path %></li>
        </ul>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>  
    <title><%= yield(:title) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="customized-container customized-g migracontainer">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>